### ISSUE TITLE
Dogfood verification

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#106]
I'm not a complete beginner and I still have trouble understanding what exactly I can actually verify with sigstore-python at the moment... It would be helpful if there was an example in the documentation of verifying e.g. that a sigstore-python release was actually built by the github action of the project.

The status at the moment seems to be:
* certificate and signature could easily be published along the artifacts (since `sign --output-*` options were just added) but currently they are not published
* There is a somewhat undocumented `verify --cert-email` option that seems to be what I want, just slightly badly named: it looks like it would allow me to check that SAN contains `URI:https://github.com/sigstore/sigstore-python/.github/workflows/release.yml@refs/tags/$VERSION`
* I imagine in addition to SAN I should verify that the signing key is a github key? Is there a process for this or should the verifying script just hardcode the keyid? Should there be an option in `verify` for this?

I'd really like to use sigstore-python for this exact purpose so I'm willing to do some work here but I think I need a bit of guidance at least: Is my understanding of how to verify that build artifacts were built by a specific github action correct? Am I missing anything with regards to my last bullet point: how do I verify that the cert actually comes from GitHub?

**Comment by jku** [comment]
> If you just want a proof that some fixed identity signed for the artifact...

I would like proof that the artifact was built by a GitHub build host using the sigstore-python workflow (and was not e.g. built by a malicious maintainer who modified the artifact). I now know how to verify that _someone_ claims that the  sigstore-python workflow was used... but I'm not sure that information is useful for me?

Maybe your comment about _querying Rekor for the identity_ is the piece that I'm missing (but i can't find more info on that). Or maybe this is just not something these signatures are good for?

**Comment by di** [comment]
Also linking https://github.com/sigstore/cosign/issues/1313 and https://github.com/sigstore/cosign/issues/1947 here, which are related.

**Comment by jku** [comment]
> I think what @jku means here is that he wants to verify that the issuer is GitHub, this should be possible by adding a flag like cosign's --cert-oidc-issuer

Yes this looks like it!

**Comment by woodruffw** [comment]
We just cut 0.5.0, so I'll work on a patch release that dogfoods verification as part of the release CI.

**Comment by jku** [comment]
Closing this could be a little premature considering that the only thing that is currently verifiable is that _some sort of build was done on a GitHub builder_ (aka checking oidc provider) -- the used project, sources or workflow aren't verifiable. But there's obviously momentum here so I'm not really complaining :)

**Comment by jku** [comment]
One more thought on this, seeing how there's some hesitation in sigstore/cosign on how and if to expose the X509 extensions to CLI (and knowing that those extensions are essential to usefully verifying build integrity -- at least without using much heavier solutions like https://github.com/slsa-framework/slsa-github-generator).

It's entirely possible that a generic signing/verifying tool like `python -m sigstore` maybe shouldn't expose those extensions in its command line interface. Instead, the project could provide a `sigstore-python-github` tool that can assert things about those extensions and can even provide a better CLI because it's not generic (obviously this tool could also be external if sigstore-python had an API).

Thoughts?

**Comment by di** [comment]
I'm kind of interested in exploring a single-file format that encapsulates all these options first, see https://github.com/sigstore/sigstore-python/issues/124

**Comment by di** [comment]
This should be possible now that #157 is resolved.

**Comment by jku** [comment]
Yeah, looks good to me. If there are further things to improve, new issues would be more useful. Closing
