### ISSUE TITLE
Release tarball differences?

### ISSUE THREAD

**Issue by jas4711** [sigstore/sigstore-python#1240]
Hi!

I'm working on Debian packaging of python-sigstore, and have to decide on which upstream source code to focus on, and there appears to be three choices:

1) git checkout of v3.5.3

2) the GitHub-generated tarball https://github.com/sigstore/sigstore-python/archive/refs/tags/v3.5.3.tar.gz

3) your uploaded tarball https://github.com/sigstore/sigstore-python/releases/download/v3.5.3/sigstore-3.5.3.tar.gz

If these contained identical files, there wouldn't be much to discuss but all three of these differ in some small ways.

Which source code do you consider the intended release?

Could you look into the differences to see if they are intentional or just the consequence of something else and consider fixing that, aligning these three source packages?

Thanks,
Simon

**Comment by di** [comment]
I think this probably depends on what Debian would prefer to build from?

* #​2 is a snapshot of the source repository and contains tests. 
* #​3  is a Python source distribution, which is built from that snapshot, does not contain tests but does contain [extra metadata](https://inspector.pypi.io/project/sigstore/3.5.3/packages/95/a2/a81fc7166e936406a6de0c2d9d23404ce3e0c345428c2d3ad6d7afb7b8ad/sigstore-3.5.3.tar.gz/sigstore-3.5.3/PKG-INFO) about the Python package.

I don't think we have any control over any differences between #​1 and #​2, but I could be wrong?

**Comment by woodruffw** [comment]
> I don't think we have any control over any differences between #​1 and #​2, but I could be wrong?

Yep, that's correct per my understanding: (1) is controlled by your `git` client and (2) is controlled by whatever knobs GitHub chooses to turn during their archival (which they've changed over the years).

I think using (3) is probably best: that's the actual source distribution as far as our own packaging is concerned. If not having tests in that distribution is a problem for Debian, then we could look at including them 🙂

**Comment by woodruffw** [comment]
Closing as non-actionable, but please let us know if shipping tests in our sdists would help with your distribution plans!
