### ISSUE TITLE
Please support cryptography-44

### ISSUE THREAD

**Issue by mgorny** [sigstore/sigstore-python#1250]
**Description**

Please add support for cryptography-44. Right now, sigstore is the only package on Gentoo systems that prevents upgrade to the newer cryptography version.

**Comment by jku** [comment]
requires #1235, #1233, #1246

**Comment by jku** [comment]
> requires #1235, #1233, #1246

These should be handled now: Unfortunately because of the rfc3161-client upgrade we also now effectively require `cryptography>=44` in main and in next release.

**Comment by mgorny** [comment]
Thanks.

**Comment by woodruffw** [comment]
> @woodruffw should we document this 44 requirement in pyproject or do something else about this? Strictly speaking we don't require any 44 API ourselves but it feels like this could be an annoying switch of a major dependency over a single release (current releases only supports < 44, next release only supports >=44)

Yeah, documenting it makes sense -- we've done similar major dep bumps of `cryptography` in prior releases without too much trouble, so I think a note should be sufficient.

Alternatively I think we *could* support `>= 43, < 45` within `rfc3161-client` without too much effort -- CC @DarkaMaul for thoughts there.
