### ISSUE TITLE
Are there any example python packages in PyPI that have been already signed using sigstore?

### ISSUE THREAD

**Issue by yunhua-deng** [sigstore/sigstore-python#126]
**Question**

Trying play `sigstore verify` but don't know where to start. Providing example PyPI packages would help newbies of sigstore.

**Comment by jku** [comment]
the sigstore-python releases themselves are signed (by the build system). Copying an example from my slack comment:
```
VERSION=0.5.1
FNAME=sigstore-${VERSION}-py3-none-any.whl
BASEURL=https://github.com/sigstore/sigstore-python/releases/download/v${VERSION}

# Download artifact, certificate and signature
wget ${BASEURL}/${FNAME}{,.crt,.sig}

# Verify that artifact was built on GitHub
python -m sigstore verify ${FNAME} \
    --cert ${FNAME}.crt \
    --signature ${FNAME}.sig \
    --cert-oidc-issuer https://token.actions.githubusercontent.com
```

You could download the wheel file from pypi and verify that one (instead of the one from github releases page as my example does).

Note that while verify "works as intended" (it verifies that the certificates key has been used to produce the signature that matches the artifact), there is very little mechanism in place so far to make sure the signature actually means something -- as an example, was it signed by a project maintainer, a build system or someone completely unrelated? If the artifact was signed by a maintainer whose identity (email) you know, you could already use `verify --cert-email` but currently the published python-sigstore artifacts are only signed by the build system.

#106 and #124 have some related future work for verifying build system signatures. 

**Maybe it would make sense for the maintainers to manually upload their signature to the release artifacts, to provide an example that users could verify?**

**Comment by woodruffw** [comment]
Thanks for the request @yunhua-deng! As @jku mentioned, we're currently self-signing `sigstore` releases with itself, but I'm not sure if any other packages are using it yet.

This has made me realize that we don't currently have that many (any?) examples of use in the README. I'll add some now.

> Maybe it would make sense for the maintainers to manually upload their signature to the release artifacts, to provide an example that users could verify?

I don't see any technical reason not to do this, although the naming scheme is going to be slightly annoying (since there are already signatures/certificates uploaded). In the mean time, I could attach a signature and certificate pair to this issue for the latest release.

**Comment by woodruffw** [comment]
#129 should add some clarifying examples, at least for `sigstore sign`. We'll have some subsequent PRs to document expected workflow for `sigstore verify`, and some CLI changes to make `sigstore verify` more ergonomic.

**Comment by yunhua-deng** [comment]
> the sigstore-python releases themselves are signed (by the build system). Copying an example from my slack comment:
> ...
> You could download the wheel file from pypi and verify that one (instead of the one from github releases page as my example does).

Thank you for pointing out this great example. The `sigstore verify` works as expected!

When exploring the source code, I realized that `/sigstore/_store/fulcio.crt.pem` (may be this is called the **trust root**?) is identical to https://github.com/sigstore/root-signing/blob/main/repository/repository/targets/fulcio_v1.crt.pem, not the v2 version (the latest version) which has the same naming `fulcio.crt.pem` in the root-signing repo. Do I need to care about this?

In my understanding, this "trust root" is the root for verifying any signing certificate, what is the mechanism or logic or pace to update it, and by who?

**Comment by yunhua-deng** [comment]
> Thanks for the request @yunhua-deng! As @jku mentioned, we're currently self-signing `sigstore` releases with itself, but I'm not sure if any other packages are using it yet.
> 
> This has made me realize that we don't currently have that many (any?) examples of use in the README. I'll add some now.
> 
> > Maybe it would make sense for the maintainers to manually upload their signature to the release artifacts, to provide an example that users could verify?
> 
> I don't see any technical reason not to do this, although the naming scheme is going to be slightly annoying (since there are already signatures/certificates uploaded). In the mean time, I could attach a signature and certificate pair to this issue for the latest release.



> #129 should add some clarifying examples, at least for `sigstore sign`. We'll have some subsequent PRs to document expected workflow for `sigstore verify`, and some CLI changes to make `sigstore verify` more ergonomic.

Are there any considerations to add verbose option, such like `sigstore verify --verbose` to show the detail of what's going on?

**Comment by woodruffw** [comment]
> When exploring the source code, I realized that /sigstore/_store/fulcio.crt.pem (may be this is called the trust root?) is identical to https://github.com/sigstore/root-signing/blob/main/repository/repository/targets/fulcio_v1.crt.pem, not the v2 version (the latest version) which has the same naming fulcio.crt.pem in the root-signing repo. Do I need to care about this?

My understanding, which might be wrong, is that the `fulcio.crt.pem` certificate is a **legacy** certificate used to sign during an earlier instance of Fulcio. `fulcio_v1.crt.pem` is the latest (and current) signing certificate, which is the correct certificate for verifying all current signatures. We currently bundle the latter and not the former, although perhaps we should also do the former (cc @di and @haydentherapper for thoughts).

> In my understanding, this "trust root" is the root for verifying any signing certificate, what is the mechanism or logic or pace to update it, and by who?

On the Sigstore side, the trust root is managed by TUF -- the repo you linked to is structured like a TUF repository, and (as I understand it) is mirrored on GCS with a standard TUF structure + signing keys. This client currently hardcodes the trust root, but the plan (#25) is to eventually use a TUF client to retrieve it. When that occurs, the "trust root" in this client will become the TUF `root.json` metadata, which provides the public key material for verifying repository artifacts.

**Comment by woodruffw** [comment]
> Are there any considerations to add verbose option, such like `sigstore verify --verbose` to show the detail of what's going on?

Yeah, we need to give this some consideration.

If you want an in-depth view into what `sigstore` is doing (and don't mind some noise), you can pass `SIGSTORE_LOGLEVEL=debug` for the time being.

**Comment by haydentherapper** [comment]
`fulcio.crt.pem` would be needed to verify old signatures. Ideally it is bundled, though it's probably fine to wait til python-tuf is integrated.

**Comment by yunhua-deng** [comment]
> My understanding, which might be wrong, is that the `fulcio.crt.pem` certificate is a **legacy** certificate used to sign during an earlier instance of Fulcio. `fulcio_v1.crt.pem` is the latest (and current) signing certificate, which is the correct certificate for verifying all current signatures.

Thanks for pointing out my misunderstanding about the trust root versions.

> On the Sigstore side, the trust root is managed by TUF -- the repo you linked to is structured like a TUF repository, and (as I understand it) is mirrored on GCS with a standard TUF structure + signing keys. This client currently hardcodes the trust root, but the plan (#25) is to eventually use a TUF client to retrieve it. When that occurs, the "trust root" in this client will become the TUF `root.json` metadata, which provides the public key material for verifying repository artifacts.

This information is very helpful for me to understand the sigstore's "magic".

**Comment by yunhua-deng** [comment]
> If you want an in-depth view into what `sigstore` is doing (and don't mind some noise), you can pass `SIGSTORE_LOGLEVEL=debug` for the time being.

Yes, this is what I did. In fact, `verbose` mode may be not that critical, and if time permits I could make a PR for this.

By the way, all the above dicussions and comments address my initial question, and you may close this issue if neccessary.

**Comment by woodruffw** [comment]
Excellent, glad to hear it!

And yes, I think a PR to add a `-V`/`--verbose` flag would be welcome. It should probably have the same effect as setting the loglevel to `debug`.
