### ISSUE TITLE
Infer signature and certificate paths from `sigstore verify`'s input

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#127]
Right now, `sigstore verify` needs to be used like this:

```bash
sigstore verify --certificate foo.crt --signature foo.sig foo
```

This has a handful of downsides:

* It violates one of the Unix tool idioms, which is that flags should never be mandatory
* It fundamentally constrains the CLI to verifying one file at a time, since `--certificate` and `--signature` can only be passed once (in theory they could be made plural, but this results in poor UX where a user must either accept quadratic verification times *or* ensure that their flag order is exactly right)

One potential solution to this is to do the converse of what we've done with `sigstore sign`, and make `--certificate` and `--signature` optional. When absent, multiple inputs will be allowed, with the following lookup scheme:

```
input.ext -> [input.ext.crt, input.ext.sig]
```

This makes the happy path _much_ cleaner:

```bash
# automatically discovers foo.tar.gz.{crt,sig}
sigstore verify foo.tar.gz

# automatically discovers .crt and .sig for each of {foo,bar}.tar.gz
sigstore verify foo.tar.gz bar.tar.gz
```

Thoughts @di?

**Comment by di** [comment]
I just meant "the behavior will be the same for globs", but also we should probably have a separate issue about testing how well this client works on windows/macos generally.
