### ISSUE TITLE
Notify on CI failure

### ISSUE THREAD

**Issue by di** [sigstore/sigstore-python#161]
**Description**

We have some tests that run on a schedule to ensure the client continues to work against Sigstore's staging instance, but we have no way to be notified if they start failing, and we'll likely move these to only run on main/cron and not on PRs (ref: https://github.com/sigstore/sigstore-python/pull/159).

We should have some way to notify maintainers when these jobs start failing, perhaps by automatically opening an issue on this repository, or email notifications.

**Comment by woodruffw** [comment]
I currently get email notifications when the staging tests fail, but I might be the only one (I wonder if it picked me because I committed the workflow?)

I'll look into some email and other notification actions, and see if there's anything that more generally fits the bill.

**Comment by woodruffw** [comment]
I did some looking around, and it seems like Slack has an official GitHub Action here: https://github.com/slackapi/slack-github-action

It supports a few different authentication methods, at least two of which (Slack Apps, incoming webhooks) should work with the current Sigstore slack (which is on the free plan).

**Comment by di** [comment]
I've also used https://github.com/peter-evans/create-issue-from-file in the past which works well

**Comment by woodruffw** [comment]
That looks nice! Keeping things on GitHub's side will also save us quite a bit of complexity/token management. I can move forwards with that.
