### ISSUE TITLE
CI: Reformatting from Black does not break `lint` workflow

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/sigstore-python#168]
A change recently went in that did not conform to Black's formatting rules. Our `lint` workflow did not catch this for whatever reason. I'm guessing that `make lint` does not exit with a non-zero exit code now.

**Comment by di** [comment]
Sorry, I'm reopening this because I think #169 is the wrong approach: https://github.com/sigstore/sigstore-python/pull/169#discussion_r926731249

**Comment by woodruffw** [comment]
#171.
