### ISSUE TITLE
Integration with SLSA security framework

### ISSUE THREAD

**Issue by diogoteles08** [sigstore/sigstore-python#222]
Hello, I'm working on behalf of Google and the [Open Source Security Foundation][https://openssf.org/] to help essential open-source projects improve their supply-chain security. I’m creating this issue to suggest the usage of the [SLSA](https://slsa.dev/) framework on your project, and expose my availability to create a PR with it.

In essence, SLSA aims to improve open source security by suggesting best practices regarding processes of artifact building and source code management, also creating [levels](https://slsa.dev/spec/v0.1/levels) of 0 to 4 that tells how closely the project is following the guidelines. Concerning the build process, SLSA highlights the importance of granting the integrity of binaries or artifacts, so that it's ensured that a binary's code really comes from the source code you’re relying on. This assurance relies on the usage of a [provenance](slsa.dev/provenance), which is verifiable and relatable to the artifact, describing where, when and how it was produced.

The sigstore-python already has solid build processes and code management, so for reaching SLSA 3 it misses only the generation of the build provenance on its releases. It would enable users to verify the integrity of the binaries and make the project even more reliable.

Would you be interested in a PR adding the provenance generation on your current build process?

**Comment by diogoteles08** [comment]
Sure! I'd only make changes on release workflow YML file. It would be necessary to create hashes of the build artifacts, and use those hashes as input for the GHA described [here](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic), which would automatically create the provenance and upload it as an output of the release. You can find an example of implementation [here](https://github.com/urllib3/urllib3/blob/main/.github/workflows/publish.yml).

With your allowance, I could also change the README to add:

1. A brief paragraph to let users know you generate provenance and encourage them to verify it when downloading your binaries.
2. A SLSA 3 badge, exposing the effort of the project around security and also encourage new adopters of SLSA, helping raise the collective level of open source security.

**Comment by woodruffw** [comment]
That sounds good to me! 

> 1. A brief paragraph to let users know you generate provenance and encourage them to verify it when downloading your binaries.

My only request is that you put this under the pre-existing "Security" header in the README, or a subheader if you feel it's more appropriate 🙂.

**Comment by diogoteles08** [comment]
Awesome! I'll create the PR and link to this Issue then. Great discussion

**Comment by diogoteles08** [comment]
May I also take this time to divide the release [file](https://github.com/sigstore/sigstore-python/blob/main/.github/workflows/release.yml) into different jobs? It would allow us to give different permissions depending on the job and would not need to have a global "content: write" permission, for example. 

I thought of the jobs build, generate-provenance and release. Take a look of how it would look like [here](https://github.com/diogoteles08/sigstore-python/blob/feat/slsa-provenance-generator/.github/workflows/release.yml).

**Comment by woodruffw** [comment]
Works for me -- having per-job permissions is ideal!

**Comment by jku** [comment]
> May I also take this time to divide the release [file](https://github.com/sigstore/sigstore-python/blob/main/.github/workflows/release.yml) into different jobs? It would allow us to give different permissions depending on the job and would not need to have a global "content: write" permission, for example.
> 
> I thought of the jobs build, generate-provenance and release. Take a look of how it would look like [here](https://github.com/diogoteles08/sigstore-python/blob/feat/slsa-provenance-generator/.github/workflows/release.yml).

:+1: this also paves the way for #44 (for that I would even split release into release-github and release-pypi so that the relevant permissions (and most importantly the pypi token) are only available when they're actually needed)

**Comment by woodruffw** [comment]
FWIW I'd prefer it if they stay in a single workflow *file*, since we can partition the permissions on a per-job basis without breaking the file up. 

(I think that's what you're doing, just making sure it's explicit!)

**Comment by diogoteles08** [comment]
Yes! That's what I'm doing, thanks for the observation.
Currently I'm dividing into the jobs build, generate-provenance, release-github and release-pypi; I'm not sure exactly which permissions they need specifically, but I'll try to search for them.
But a question: is it ok to keep the "sign" step inside the build job?

**Comment by woodruffw** [comment]
> But a question: is it ok to keep the "sign" step inside the build job?

I have a slight preference for that, since we currently use it to smoketest the release right after we build it. It also avoids having to wrangle things through workflow artifacts.

**Comment by diogoteles08** [comment]
Just created the PR: https://github.com/sigstore/sigstore-python/pull/223
