### ISSUE TITLE
PR requirements not listed in CONTRIBUTING.md

### ISSUE THREAD

**Issue by diogoteles08** [sigstore/sigstore-python#224]
**Description**

Hello! I'm making my first contribution to the repo and when I was about to create the PR I faced the following requirements:
```
- ensure your commits are signed-off, as sigstore uses the [DCO](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) using `git commit -s`, or `git commit -s --amend` if you want to amend already existing commits
- lastly, ensure there are no merge commits!
```
But the thing is that those requirements were not listed on the CONTRIBUTING.md, so some people (including me haha) could end up having to redo some work.

I think a good idea would be update the CONTRIBUTING.md text to add those requirements.
If you agree, I would be happy to raise a PR with that =)

**Comment by woodruffw** [comment]
Hmm, do we actually enforce the absence of merge commits? I do merges as part of my local workflow, so I didn't think we do. If they are present, we usually just squash them out if necessary.

**Comment by di** [comment]
> Hmm, do we actually enforce the absence of merge commits?

No, I don't believe we do.

**Comment by woodruffw** [comment]
Yeah, so let's leave that out. Otherwise, adding guidance around signoffs is a good addition!
