### ISSUE TITLE
Rekor Verification Reliability: Using /entries/retrieve rather than /index/retrieve

### ISSUE THREAD

**Issue by asraa** [sigstore/sigstore-python#237]
https://github.com/sigstore/sigstore-python/blob/67b0c0dda70859ce5d8912ad47c9a63ee2975b4f/sigstore/_verify.py#L251-L252

Hi all!

I was cleaning up an AI due to a post-mortem (https://github.com/sigstore/public-good-instance/pull/871, I'm aware this is not a public repository). This postmortem was on the issue that Rekor production was sharded, and originally Rekor was only searching for entries on the current active shard through the `/entries/retrieve` endpoint. This would mean that if a signature was uploaded before the instance sharded, it would not be found.

As a result, I had an AI to inform clients that they may need to be shard-aware. Users are able to upload the same entry to multiple shards, which means that when clients use `/entries/retrieve` to get an entry by the (sig, msg, cert) pair, that they may return multiple entries (on multiple shards). Obviously, the earliest entry should be used (because the integratedTime there is TRUE, later entries on later shards are "dupes" that someone uploaded later).

Then, I did some inspection into sigstore-python, and I found it was using `/index/retrieve` to get UUIDs for signature entries. Did you know that the endpoint is experimental and the index has no stability guarantee of verifiability?
https://github.com/sigstore/rekor/issues/1021

Ideally you should not be using this endpoint.

Because you have the certificate in that `_verify` function, you should be querying Rekor by the proposed entry with the (sig, msg, cert) pair through `/entries/retrieve`. This is a verifiable endpoint.

That being said, after sharding, clients have to be aware that they need to extract the earliest entry retrieved (the entry on the earliest shard, as described above).

I can provide more details later, or even help to craft a PR!

**Comment by woodruffw** [comment]
Thanks! I was not aware that `/index/retrieve` was unstable.

So, just to make sure I understand: instead of using either the log index or UUID via `/index/retrieve`, we should use the tuple of `(sig, msg, cert)` via `/entries/retrieve`, correct? And the payload of that endpoint will be similar to what we currently expect, i.e. a Rekor log entry?

> I can provide more details later, or even help to craft a PR!

That would be extremely helpful, thank you! I'm also happy to do the PR sometime today or tomrorow (after experimenting a bit), if you're busy.

**Comment by asraa** [comment]
@woodruffw : quick ask: it looks like the `entries.retrieve` endpoint isn't implemented ([this](https://github.com/sigstore/rekor/blob/27a25e03588b051afc5e89b9502d6cd4cf63e58b/openapi.yaml#L218) one): this searches for entry either by proposed entry, log index, or UUID (we're only interested in the proposed entry, and impl looks **almost** identical to `RekorEntries` post method): do you think we can split some work here? If you can add this endpoint (whenever you have time), which may return multiple entries, I can work on the verification side.

**Comment by woodruffw** [comment]
> If you can add this endpoint (whenever you have time), which may return multiple entries, I can work on the verification side.

Sounds good to me. I'll have some time this afternoon!
