### ISSUE TITLE
Chore: use newtypes to make the API more misuse-resistant

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#249]
This issue is just a reminder for myself.

We have a few internal APIs that take sequences of `str` parameters, where each is a base64 (or not-base64) encoded signature, PEM-encoded certificate, etc. It's easy to potentially forget a layer of base64 encoding or decoding with these.

Some `typing.NewType` usage would help here:

* `b64str` for a string that's base64-encoded
* `pemcert` for a string that contains a PEM-encoded certificate (**not** wrapped in another layer of base64)

**Comment by woodruffw** [comment]
Some students at Purdue have volunteered to take a stab at this, so I've removed the request for help.

**Comment by woodruffw** [comment]
No problem! Feel free to ping me either here or on the Sigstore Slack if you have any other questions.

**Comment by emilejbm** [comment]
Emile here! Thanks for all the help William.

**Comment by emboman13** [comment]
We're currently working on https://github.com/emilejbm/sigstore-python. We've changed some files to use NewTypes specified in newtypes.py. Give us a shout if anything looks incorrect or if we've misinterpreted what you wanted us to do. Specifically, changes to sign.py and verify/models.py

**Comment by woodruffw** [comment]
> Give us a shout if anything looks incorrect or if we've misinterpreted what you wanted us to do. Specifically, changes to sign.py and verify/models.py

Would you mind opening a draft PR for your changes? That would make it much easier to do an initial round of review 🙂

**Comment by woodruffw** [comment]
#474.
