### ISSUE TITLE
Refactor SCT verification/CT key handling

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#263]
This has come to light during the staging instance's recent sharding: there are now multiple CT signing keys, instead of just `ctfe.pub`. The newer signing keys aren't necessarily compatible with the older ones (i.e. they can be ECDSA instead of RSA), and new CT entries are signed with the latest key rather than the older ones.

As a result, our assumption of a single CT key (`ctfe.{staging.}pub`) is no longer correct. This makes SCT verification fail for newer SCTs, since they're no longer signed with the key that we've vendored.

To fix this, we need to refactor our CT key handling. In particular:

* Instead of a single CT key, we need a "keychain" of CT keys. That keychain will be essentially a `dict[KeyID, Key]`, where `KeyID` is the key ID format described in [RFC 6962 s. 3.2](https://www.rfc-editor.org/rfc/rfc6962#section-3.2). 
* When verifying an SCT, the keyring will select the correct CT key using the SCT's `logID` field, which is really just the key ID.

For the time being, we'll create this keychain by vendoring more CT keys (#262). Longer term, the TUF integration planned under #25 will be expected to retrieve all CT key targets, either via their usage metadata or some other identifying feature in the TUF repo.

**Comment by woodruffw** [comment]
#262 will vendor the new staging instance CT keys. From there, we'll need the keyring impl.

**Comment by asraa** [comment]
Looks good to me!

Another refactoring benefit: I would suggest moving CTFE keys out of the rekor instance (https://github.com/sigstore/sigstore-python/blob/a5091e5485528ec57396d1a7ece53ed53cf1a70e/sigstore/_sign.py#L100) and into its own module or next to fulcio -- rekor actually has no interaction with it, but fulcio does post it's certs to it (ct for certs, rekor for signing events).

**Comment by woodruffw** [comment]
#267 has the initial refactor here.

> I would suggest moving CTFE keys out of the rekor instance

I agree, although JFYI I didn't include this change in that refactor (yet). I want to think a bit more about how that'll look with the other refactor I have planned (#250).
