### ISSUE TITLE
Add CLI options compatible with `cosign` where applicable

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/sigstore-python#27]
We should look at what flags that `cosign` provides and consider adding them to `sigstore-python`. Some examples that we've already identified include controlling the URL of the Fulcio and Rekor instances that we call out to.

**Comment by woodruffw** [comment]
Closing this in favor of more precise issues going forward, now that we're at parity with the relevant parts of `cosign` 🙂
