### ISSUE TITLE
Implement a sign/verify API callable from Python

### ISSUE THREAD

**Issue by mbestavros** [sigstore/sigstore-python#273]
**Description**

Currently, `sigstore-python` only exposes a simple sign/verify API through its CLI. It's likely that some Python projects interested in integrating sigstore would benefit from a similar interface available directly in code.

cc @lukehinds @mayaCostantini

**Comment by di** [comment]
I think this is probably a duplicate of https://github.com/sigstore/sigstore-python/issues/4?

**Comment by woodruffw** [comment]
Yes, I believe so. We do currently have simple sign/verify APIs (under `sigstore._sign` and `sigstore._verify`), but they're considered internal for the moment and are subject to major changes between releases.

**Comment by mbestavros** [comment]
Yep, I'll close this.
