### ISSUE TITLE
using sigstore python as a python library

### ISSUE THREAD

**Issue by javixeneize** [sigstore/sigstore-python#283]
Hi

Is this module ready to be used as a library inside a python application?

I am trying this

import sigstore._sign as sign

signer = sign.Signer()

signer.sign(image.encode('utf-8'), identity_token=key)

But it is returning 

jwt.exceptions.DecodeError: Not enough segments

Thanks

Note what i am trying to do is the equivalent of this in the CLI

cosign sign --key my.key image

**Comment by woodruffw** [comment]
Hi! Thanks for the question.

This is part of our stabilization roadmap, and is tracked under #4.

For the time being, you should *not* use the private APIs under the `_sign` and `_verify` modules -- they're considered unstable, and we make significant changes to them between releases.

As a result, until we have a 1.0 release, the only semi-stable interface for sigstore-python is the `sigstore` CLI. 

I'm closing this as a duplicate, but please feel free to subscribe to #4; we welcome feedback and thoughts on how these APIs should look.
