### ISSUE TITLE
Scorecard analysis failing

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/sigstore-python#291]
As of 1730a995465796183f67603f2532988c75a51e4b, this job seems to be failing in CI.

The first occurrence is here: https://github.com/sigstore/sigstore-python/actions/runs/3378469524/jobs/5608710169

**Comment by spencerschrock** [comment]
Hi, take a look at https://github.com/ossf/scorecard-action/issues/997
`sigstore/cosign` had some breaking changes, so updating to `scorecard-action` v2.0.6 should fix the failures.

**Comment by woodruffw** [comment]
Thanks @spencerschrock! I'll look into updating now.

**Comment by woodruffw** [comment]
#293 should address this.
