### ISSUE TITLE
Trying to sign using GitHub OIDC doesn't work

### ISSUE THREAD

**Issue by jcea** [sigstore/sigstore-python#300]
**Description**

Trying to sign a file using Github as OIDC provider send you to a "file not found page"

Steps:

1. $ sigstore sign FILE
2. The browser in invoked. Select "github".
3. You get a "404 file not found" error.

**Version**

Using current PYPI version, 0.7.0

**Comment by di** [comment]
To be clear, you arrived on the page at https://oauth2.sigstore.dev/, which looked like this:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/294415/202348392-764c2421-578e-4cc2-9bb1-ee5b149606cf.png">

And then when you clicked "Log in with GitHub", it gave you a 404?

**Comment by jcea** [comment]
https://oauth2.sigstore.dev/ gives me "404".

Running ```sigstore sign FILE``` in the terminal, I see this:

```
Waiting for browser interaction...
command= "/home/jcea/waterfox/waterfox" args= ("/home/jcea/waterfox/waterfox", "http://localhost:41517")
Copying QUrl("http://localhost:41517/")  to QUrl("file:///home/jcea/.cache/kioexec/krun/881819_0/unnamed")
Telling kioexecd to watch path "/home/jcea/.cache/kioexec/krun/881819_0/unnamed" dest "http://localhost:41517/"
All files downloaded, will call slotRunApp shortly
EXEC "/home/jcea/waterfox/waterfox /home/jcea/.cache/kioexec/krun/881819_0/unnamed"
EXEC done
Waiting for browser interaction...
command= "/home/jcea/waterfox/waterfox" args= ("/home/jcea/waterfox/waterfox", "http://localhost:41517")
Copying QUrl("http://localhost:41517/")  to QUrl("file:///home/jcea/.cache/kioexec/krun/881819_0/unnamed")
Telling kioexecd to watch path "/home/jcea/.cache/kioexec/krun/881819_0/unnamed" dest "http://localhost:41517/"
All files downloaded, will call slotRunApp shortly
EXEC "/home/jcea/waterfox/waterfox /home/jcea/.cache/kioexec/krun/881819_0/unnamed"
EXEC done
```

A browser window appears. I click on "github", and the link send me to https://github.com/login/oauth . Github gives a 404 for that URL.

**Comment by jcea** [comment]
Clicking on Google or Microsoft options send me to login screens correctly, Github gives back a 404.

**Comment by di** [comment]
Also, to isolate whether this is specific to the Python client or not, can you try signing with

**Comment by woodruffw** [comment]
Additionally: could you try re-running with `SIGSTORE_LOGLEVEL=debug` and pasting the log (modulo any secret URLs) here?

**Comment by woodruffw** [comment]
(I was able to confirm that `python -m sigstore sign --staging` works with the GitHub OIDC provider for me locally. I'll test with the production instance in a moment.)

**Comment by woodruffw** [comment]
Confirmed that signing with the production instance also works for me.

**Comment by jcea** [comment]
The problem seems to be that the URL is relative, not absolute. That it, the real URL in the buttons I see are in the form: "file:///auth/auth/https:%252F%252Fgithub.com%252Flogin%252Foauth?client_id=sigstore&...". They miss the "https://oauth2.sigstore.dev/" at the beginning.

I am running KDE, seems like the page is downloaded and the downloaded version is passed to my browser, instead of the proper URL.

I can reproduce the issue doing this in a python CLI:

```
Python 3.11.0 (main, Oct 25 2022, 03:00:30) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import webbrowser
>>> webbrowser.open("https://www.jcea.es/")
True
>>> command= "/home/jcea/waterfox/waterfox" args= ("/home/jcea/waterfox/waterfox", "https://www.jcea.es/")
Copying QUrl("https://www.jcea.es/")  to QUrl("file:///home/jcea/.cache/kioexec/krun/1641521_0/unnamed")
Telling kioexecd to watch path "/home/jcea/.cache/kioexec/krun/1641521_0/unnamed" dest "https://www.jcea.es/"
All files downloaded, will call slotRunApp shortly
EXEC "/home/jcea/waterfox/waterfox /home/jcea/.cache/kioexec/krun/1641521_0/unnamed"
EXEC done
``` 

Ok, this seems to be a bug in Python. I will triage it.

Sorry for the noise.

**Comment by jcea** [comment]
I close this bug, since it resides in Python, not sigstore.

Sorry for wasting your time.
