### ISSUE TITLE
Support for an importable CLI

### ISSUE THREAD

**Issue by mayaCostantini** [sigstore/sigstore-python#313]
**Description**

As a developer of Python tools with support for content signing and verification, I would like to integrate sigstore capabilities directly in existing command line interfaces, for example as an alternative to signing and verifying content with GPG.

This issue occurred to me when trying to add sigstore support for the [ansible-sign](https://github.com/ansible/ansible-sign) CLI, which currently signs Ansible content files using GPG keys. Instead of copying the command line arguments and of reproducing the same logic for the private `_sign` and `_verify` methods there, it would be practical to import sigstore subcommands and arguments via a public interface to extend an existing command line script. The CLI configuration could be implemented in a public class instantiated by the user instead of having parameters directly passed to a parser.

This implementation could be useful for a number of CLI tools currently using GPG (my first thought was for package managers such as [dnf](https://github.com/rpm-software-management/dnf), but other examples might exist), and probably provides a better option than reproducing the logic present in the `_cli.py` file or maintaining a wrapper and risk breaking the tool if a change in API occurs.

**Comment by di** [comment]
I'm not sure I understand what an "importable CLI" is. Do you mean an importable API? If so, I think this is likely a duplicate of #4.

**Comment by mayaCostantini** [comment]
Sorry if my explanation was not clear. What I meant by "importable CLI" is a way to import directly the argparse command line options and the `_sign`, `_verify` and `_get_identity_token` methods so that they could be reused within other argparse command line tools without having to copy them by hand.

For example, this could be done by representing the sigstore-python command line as a public `SigstoreCLI` class:

```
# File: sigstore/cli.py

class SigstoreCLI:

    sign_arguments = (
        StagingOption,
        RekorUrlOption,
        OIDCClientIdOption,
        ...
     )

     verify_arguments = (
        VerifyCertificateOption,
        VerifySignatureOption,
        VerifyRekorBundleOption,
        ...
     )
     
     def add_sign_arguments(self, parser):
         for sign_arg in sign_arguments:
              parser.add_argument(sign_arg.name_or_flags, **sign_arg.arguments())

    ...

    @classmethod
        def sign(self, args):
             # _sign method logic
    
    @classmethod
        def verify(self, args):
             # _verify method logic

...
```

With argparse arguments represented as

```
@dataclass
class _ArgparseArgument:
    
    name_or_flags: Union[str, list]
    action: Optional[str]
    ...
	
    def arguments(self):
        cli_arguments = self.__dict__
        del cli_arguments["name_or_flags"]
        return cli_arguments

...

StagingOption = _ArgparseArgument(
    name_or_flags="--staging",
    action="store_true",
    default=_boolify_env("SIGSTORE_STAGING"),
    help="Use sigstore's staging instances, instead of the default production instances"
)
```
 
On the user side, arguments could be added this way:

```
...
from sigstore.cli import SigstoreCLI

cmd_sigstore_sign = some_external_cli_parser.add_parser(
            "sigstore-sign",
            help=("Subcommand to sign an artifact with Sigstore.")
        )
cmd_sigstore_sign.set_defaults(func=SigstoreCLI.sign)
SigstoreCLI.add_sign_arguments(cmd_sigstore_sign)
```

This is only an implementation idea and it would need some improvements, but it roughly illustrates how I imagined users adding sigstore CLI functionalities to their own argparse CLIs.

I thought this would be a nice utility if more CLI tools were to adopt Sigstore as a subcommand to sign / verify artifacts.
However if you think this feature request is too out of scope / specific / other, please feel free to close it.

**Comment by woodruffw** [comment]
Oh, I see what you're going for!

Yeah, I don't _think_ we want to provide the current CLI implementation as an importable API -- it happens to be based on `argparse` at the moment because `argparse` strikes the right balance between our requirements, but that's just an implementation detail that we might change between releases.

I might be missing it, but I don't see a ton of value in us providing an importable CLI rather than eventually stabilizing the Python API (per #4) -- if people _really_ want to embed our CLI, they can always wrap the `sigstore` CLI itself as a subcommand and dispatch through it. But I wouldn't necessarily recommend that until we do a stable release, since there's a high probability that we'll continue to change `sigstore`'s CLI flags 🙂

**Comment by mayaCostantini** [comment]
I see, thanks for the clarification! Yes, this would introduce some complexity and to be honest, I am not too comfortable either with this being dependent on argparse. I will go ahead and close this issue, feel free to reopen if needed.
