### ISSUE TITLE
Transfer to `sigstore` org

### ISSUE THREAD

**Issue by di** [sigstore/sigstore-python#32]
Transfer this repo to https://github.com/sigstore and make all the necessary updates to docs/URLs.

**Comment by di** [comment]
FYI: https://github.com/sigstore/TSC/issues/10

**Comment by di** [comment]
@woodruffw or @tetsuo-cpp, can you add @lukehinds as a collaborator here so he can make the transfer?

**Comment by tetsuo-cpp** [comment]
@di 
Sure! It seems that we need an "owner" of the Trail of Bits GitHub org to add @lukehinds since he's external to the org.

I'm asking around internally to get someone to do this for us. Will get back to you when I hear more.
