### ISSUE TITLE
Use the new and improved Sigstore redirect page

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#354]
We should crib the work done in https://github.com/sigstore/sigstore/pull/876 and reuse it here!

**Comment by woodruffw** [comment]
Setting this as a 1.0 goal, since it's a nice UX improvement for `sigstore sign` users.

**Comment by woodruffw** [comment]
@tetsuo-cpp I tagged both of us on this just in case you have time for it today; otherwise I'll tackle it tomorrow :slightly_smiling_face:

**Comment by tetsuo-cpp** [comment]
Sure, I'll have time to start on this today.

**Comment by di** [comment]
Before this gets closed by #356, can we create a new issue to find a way to ensure this is up to date and matches what `cosign` does? I imagine we'll want to keep these in sync (but also this is fine for 1.0 as is).

**Comment by woodruffw** [comment]
> Before this gets closed by #356, can we create a new issue to find a way to ensure this is up to date and matches what `cosign` does? I imagine we'll want to keep these in sync (but also this is fine for 1.0 as is).

Yep, I'll file that now.
