### ISSUE TITLE
actions/checkout seemingly not updated by dependabot

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#358]
Most workflows use `actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf`: dependabot does not seem to update it.

This is not a commit that exists in the checkout repository -- or rather, it must exist in the remote since the workflows run successfully but it's not part of the published git repository.

A wild guess: this is the SHA of a tag object (like "v2") instead of a commit. GitHub moves these tags around, meaning the tag "v2" still exists but the SHA is different, so the old SHA is now a dangling reference.

**Comment by jku** [comment]
> jku added the enhancement label now

That should have been "bug" really but I can't change it anymore

**Comment by tetsuo-cpp** [comment]
Interesting, I'll check this out now.
