### ISSUE TITLE
_internal/tuf: Avoid constant metadata updates

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#376]
**Description**

Joshuas original TUF PR and the "sigstore TUF client" design doc contain the idea of not fetching remote metadata if it's not required:
* the PR just checked if timestamp was expired or not
* the doc invents a "client metadata cache validity" configuration item

I did not include either approach in the merged TUF implementation as it felt unnecessary for v1 and not completely ready. The rough idea still makes sense: e.g. a CI calling `sigstore verify` a thousand times in a row should work, and there should be no need to make the root and timestamp requests that TUF clients normally do at startup more than once during those thousand calls.

I've made an experimental [PR](https://github.com/theupdateframework/python-tuf/pull/2251) for python-tuf that tries to implement the timestamp expiry idea a bit more robustly but I don't think this is purely a python-tuf feature, sigstore-python is going to need changes as well:
* what is the policy that sigstore-python actually wants? is _"timestamp is valid and verify succeeds"_ good enough for sigstore-python, or should there be an additional _"we've updated tuf metadata less than X days ago"_ requirement
* how do we deal with e.g. verify failure because the signature uses a key/cert that we don't know about because we're using three days old certs and new ones were published yesterday? This is a bit complicated but certainly possible:
   * try to verify using tuf, allowing caching
   * if verify fails (maybe with specific failures), retry silently but this time force tuf update

**Comment by jku** [comment]
> how do we deal with e.g. verify failure because the signature uses a key/cert that we don't know about because we're using three days old certs and new ones were published yesterday?

Very careful repository maintenance would actually solve this:
* repository could publish keys/certs for verifiers two weeks (timestamp expiry period) before they are made available to signers -- e.g. fulcio cert could be added in the metadata before the instance starts signing with that root cert
* this way verify couldn't fail because of missing certs even if caching was used

but maybe this is too much to ask from maintenance?

**Comment by haydentherapper** [comment]
> repository could publish keys/certs for verifiers X weeks (timestamp expiry period) before they are made available to signers -- e.g. fulcio cert could be added in the metadata before the instance starts signing with that root cert

I don't think this is a burden on maintainers, this is what's necessary to not break clients. We did this with the CT log key rotation for example. We first included the key in the target metadata, waited until all clients' local timestamps should have expired (the timestamp expiration period of 1 week), and then rotated the log.

**Comment by jku** [comment]
> this is what's necessary to not break clients.

Note that with TUF spec-compliant clients it explicitly is not necessary-- in TUF timestamp expiration does not define the time that _clients_ can avoid updating, it defines the the time that repository can avoid updating. Clients must update every single time...

But I do agree that (once we have this ironed out) it might make sense for sigstore to
1. document that clients can avoid updating metadata every time (even it's non-compliant with TUF spec)
2. promise to maintain services in a way that ensures clients will not encounter unknown key material when doing this

**Comment by woodruffw** [comment]
xref https://github.com/theupdateframework/python-tuf/pull/2251 (now closed, but a good example of a working start/basis here.)

IMO we can consider this lower-priority now that Sigstore's TUF repo will contain "bundled" trust roots -- that'll the number of network round-trips before first Sigstore sign/verify substantially.

**Comment by woodruffw** [comment]
#1143 will address this.
