### ISSUE TITLE
Finalize importable `sigstore` API

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/sigstore-python#4]
Once we've written the Fulcio and Rekor clients, we should be fill out the importable API. The API should roughly line up with the subcommands that `cosign` supports.

The CLI itself (which we'll implement in #3) will be a thin wrapper that wires the `argparse` flags to the API. So the meat of the CLI logic will be covered in this task.

I expect that we'll separate this into multiple issues when we begin working on it.

**Comment by tetsuo-cpp** [comment]
This is a great article that explains what `cosign` is doing under the hood: https://martinheinz.dev/blog/56

**Comment by tetsuo-cpp** [comment]
One thing I'd like to do here is to use `logging` throughout the API for more fine-grained reporting so that we can ask users to turn logging to `debug` before filing issues.

Then for actual feedback that we're using `output` for, we can follow a similar model to `pip-audit`'s `AuditState` where we can let users capture and use the output in whatever way they want.

**Comment by di** [comment]
Changed this to 'finalize' instead of implement and moved it to the 1.0 milestone.

**Comment by woodruffw** [comment]
xref #250 for some changes that will happen to these APIs before stabilization.

**Comment by woodruffw** [comment]
For visibility: #299 is going to refactor the verification API per #250, which will get us much closer to a stabilize-able public API.

**Comment by mayaCostantini** [comment]
Thanks a lot @woodruffw !

**Comment by tetsuo-cpp** [comment]
I'm going to make a separate issue to begin generating API docs like we do for `pip-audit`.

**Comment by woodruffw** [comment]
@mayaCostantini we've just cut 0.10.0, which has the first official iteration of the stable API 🙂 

The docs are here: https://sigstore.github.io/sigstore-python/

**Comment by mayaCostantini** [comment]
Amazing, thanks @woodruffw !
