### ISSUE TITLE
provide api for use by applications

### ISSUE THREAD

**Issue by ht-thomas** [sigstore/sigstore-python#423]
**Description**

I've noticed that sigstore is primarily written to be a command line tool, however I'm working on a project that needs to verify packages signed with sigstore. The project is meant to be an application that will be packaged by pyinstaller so we don't assume the host system on which the application will be installed has python setup to use sigstore for verifcation. Can we work on an API that can be exposed to the application to carry out this task? I have been using subprocess but I think having an API would be better

**Comment by woodruffw** [comment]
> Can we work on an API that can be exposed to the application to carry out this task? I have been using subprocess but I think having an API would be better

We'll do you one better: there is a stable API, as of `0.10.0`, and it'll be finalized with the upcoming `1.0` release! 

You can find the documentation here: <https://sigstore.github.io/sigstore-python/sigstore.html>

There will be some small changes between the two (mostly just renmaings), so we encourage you to play around with them in their current form and report any questions you have 🙂

**Comment by woodruffw** [comment]
Just for xref: dupe of #4.

**Comment by ht-thomas** [comment]
thanks @woodruffw . I went through the code and realized there was an API. it just wasn't documented so I thought we only had a commandline option. I've already began integrating it in the project I'm working on.
