### ISSUE TITLE
Pinned versions of `cryptography` and `pyOpenSSL` are incompatible

### ISSUE THREAD

**Issue by mayaCostantini** [sigstore/sigstore-python#447]
**Description**

The `cryptography` package in version `>=39` as pinned in the project dependencies needs `pyOpenSSL==23.0.0`.
Versions inferior to `22.1.0` cause the following error:

```
Traceback (most recent call last):
  File "/home/mcostant/.local/bin/sigstore", line 5, in <module>
    from sigstore._cli import main
  File "/home/mcostant/.local/lib/python3.8/site-packages/sigstore/_cli.py", line 46, in <module>
    from sigstore.verify import (
  File "/home/mcostant/.local/lib/python3.8/site-packages/sigstore/verify/__init__.py", line 60, in <module>
    from sigstore.verify.verifier import (
  File "/home/mcostant/.local/lib/python3.8/site-packages/sigstore/verify/verifier.py", line 32, in <module>
    from OpenSSL.crypto import (  # type: ignore[import]
  File "/home/mcostant/.local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/mcostant/.local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

but `pyOpenSSL` in version `22.1.0` requires `cryptography<39`, which is incompatible with `sigstore`. Pinning `pyOpenSSL` to version `23.0.0` should fix the issue.

For reference:
https://github.com/pyca/cryptography/issues/7959#issuecomment-1368711852

**Version**

Version 1.0.0

**Comment by woodruffw** [comment]
Thanks for the report!

Out of curiosity: are you seeing this manifest in some of your `sigstore-python` installs? We have `pyOpenSSL==23.0.0` in the fully hashed requirements here:

https://github.com/sigstore/sigstore-python/blob/main/install/requirements.txt

...and in general `pip` should always select the latest compatible version for the default `pip install sigstore`. So users should almost never see this incompatibility, unless they're installing `sigstore` into an environment that has a pre-existing older `pyOpenSSL`.

(Either way, we should definitely fix this, and I'll make a PR for it in a moment!)

**Comment by woodruffw** [comment]
Opened #448 with the fix.

**Comment by mayaCostantini** [comment]
I tried installing `sigstore` outside of a virtual environment which might have contained an older version of `pyOpenSSL`. Thanks for the fix!
