### ISSUE TITLE
Support globs for filenames

### ISSUE THREAD

**Issue by di** [sigstore/sigstore-python#48]
Similar to `cosign`, this library should support passing globs as filenames. Currently, it fails:

```
$ sigstore sign --identity-token=$(...) dist/*
Usage: sigstore sign [OPTIONS] FILE
Try 'sigstore sign --help' for help.

Error: Invalid value for 'FILE': 'dist/*': No such file or directory
```

**Comment by woodruffw** [comment]
Specifically, I assume we should let the shell expand globs rather than expand them ourselves, right? So both of these should work:

```
sigstore sign ... dist/*
sigstore sign ... dist/foo dist/bar
```

**Comment by di** [comment]
> we should let the shell expand globs rather than expand them ourselves

That's true on *nix systems, but isn't true for Windows. I'm not sure what the `click` best practices are here, but I'm assuming they have us covered.

**Comment by woodruffw** [comment]
> That's true on *nix systems, but isn't true for Windows. I'm not sure what the `click` best practices are here, but I'm assuming they have us covered.

Yeah, it looks like `click` has our back on Windows: https://github.com/pallets/click/pull/1830
