### ISSUE TITLE
Release: sign via ambient credentials

### ISSUE THREAD

**Issue by di** [sigstore/sigstore-python#50]
**Description**

Once this library supports ambient credential detection in #31, we should update our release workflow to sign via GitHub's ambient OIDC identity instead of explicitly requesting it.

Blocked on #31.

**Comment by woodruffw** [comment]
From conversation: we should do this ambient detection by default, but also allow users to explicitly disable it (e.g. with `--no-ambient`).

Here's one possible order of precedence (from highest to lowest):

1. Explicit identity token via `--identity-token=...`
2. Ambient credential from one of many sources (environment, REST endpoint, etc.)
3. Interactive OAuth flow

**Comment by di** [comment]
Let's not add any flags to disable ambient credential detection until we get some feedback on https://github.com/sigstore/cosign/issues/1819.

**Comment by woodruffw** [comment]
The groundwork here is all done, we just need to add more ambient detectors (which is tracked separately.)
