### ISSUE TITLE
Update our release process to produce `.sigstore` bundle files

### ISSUE THREAD

**Issue by di** [sigstore/sigstore-python#509]
**Description**

Currently because we specify filenames for `.sig` and `.crt` outputs, we aren't generating a bundle: https://github.com/sigstore/sigstore-python/blob/bb1ec9fa19611c7fd226c6254e70eb0b3564e1e6/.github/workflows/release.yml#L52-L55

We should update this to generate a `.sigstore` file as well. Additionally, we should test verification with both the `.crt`/`.sig` combination and the `.sigstore` bundle separately.

**Comment by woodruffw** [comment]
Makes sense to me!

How do you feel about switching to `gh-action-sigstore-python` for our release process? Previously we did this as a "smoke test" to ensure that we weren't pushing a broken release, but I think our improved code coverage + regular conformance suite runs make that less of an issue in the release path. That action also already supports `.sigstore` bundles, so we could simplify the CI a bit here.

**Comment by di** [comment]
I still kind of like the ability to use the to-be-released version to sign: this ensures that if we ever have a breaking change that causes all older versions to fail, we could still release and sign the release.

Maybe `gh-action-sigstore-python` could take a path to distribution for `sigstore-python` and install that instead of from PyPI? Not sure if that would work given we'd need to share the file between workflows.

**Comment by woodruffw** [comment]
Makes sense! We'll do it without the full separate action for now 🙂
