### ISSUE TITLE
Replace our ambient credential detection with `id`

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#528]
`id` is now on PyPI (https://pypi.org/project/id/), and contains almost exactly the same APIs we have internally for ambient credential detection. We should switch to it.

**Comment by woodruffw** [comment]
CC @tnytown

**Comment by tetsuo-cpp** [comment]
I need to touch this as part of my BuildKite OIDC support. Might be easier for me to just do this.

**Comment by woodruffw** [comment]
Yeah, good point. Go for it!
