### ISSUE TITLE
confusing debug output in sign

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#564]
Signer.sign() does this:
```
logger.debug(f"cert-oidc-issuer: {oidc_identity.issuer}")
```

That makes it sound like I'm being shown the value that ends up as the signing certificate claim "Issuer" (1.3.6.1.4.1.57264.1.1), but I'm not as the printed value can be (and usually is) the sigstore dex proxy ("https://oauth2.sigstore.dev/auth").

Maybe the best solution is 
* debug print the oidc issuer `f"oidc-issuer: {oidc_identity.issuer}"`
* as special case, if there is a federated issuer, print `f"oidc-federated-issuer: {oidc_identity.connector_id}"` (the connector_id is currently not exposed but that should be easy)

cc @lukpueh

**Comment by woodruffw** [comment]
I believe this is covered with #635!
