### ISSUE TITLE
`sigstore sign`: `--output-directory` or similar option for writing all outputs to a single directory?

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#620]
As raised by @alex: `sigstore sign` currently places each signing artifact adjacent to its corresponding input, which may not be ideal for some users.

To accommodate users who would like to write all signing artifacts to a single directory instead, we could support `--output-directory` or similar. For example:

```bash
# writes a/a.sigstore, b/b.sigstore
sigstore sign a/a b/b

# writes x/a.sigstore, x/b.sigstore
sigstore sign --output-directory x a/a b/b
```

**Comment by woodruffw** [comment]
CC @di for opinions on whether we ought to support this 🙂

**Comment by di** [comment]
I don't see why not!

**Comment by woodruffw** [comment]
Cool! I queued this up for both myself and @tnytown; we'll coordinate on who tackles it.
