### ISSUE TITLE
Remove deprecated `sigstore verify -> sigstore verify identity` alias

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#636]
As part of the 2.0 release, we should remove this deprecated alias: it complicates argument parsing significantly, and has been marked for deprecation since 1.0.

Expected new behavior: `sigstore verify` without a subcommand will produce a hard error and a suggested list of subcommands, rather than producing a deprecation warning and redirecting the user to `sigstore verify identity`.

CC @di for visibility.

**Comment by di** [comment]
Agreed!

**Comment by woodruffw** [comment]
See #642.
