### ISSUE TITLE
CLI-based browser cannot complete OAuth flow

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/sigstore-python#661]
**Description**

I tried using the CLI to sign some files. When it does not find an ambient identity (or if I disable it with  `--oidc-disable-ambient-providers`), the CLI automatically launches a CLI-based browser. I'm not sure where it picks it from, but in the end OAuth flow fails - it complains the browser does not support Javascript. Even if it did, I'd rather have it launch the UI-based browser.

Anything I can do?

**Comment by woodruffw** [comment]
Thanks for the report!

Can you say more about your setup? We use `webbrowser.open` to open the user's "default" browser:

https://github.com/sigstore/sigstore-python/blob/85f7071fe6291ccf5fc907e4d5345dc478c44ac6/sigstore/oidc.py#L269

According to the docs (https://docs.python.org/3/library/webbrowser.html), `webbrowser.open`'s default behavior is system-specific, but includes searching the `BROWSER` environment variable, if set. Do you have that set?

**Comment by woodruffw** [comment]
Also, in the future: please use the dedicated bug template! That template gives us additional context that makes triaging these kinds of possible bugs much faster.

**Comment by woodruffw** [comment]
For additional context: here's `webbrowser`'s discovery logic: 

https://github.com/python/cpython/blob/a6326972253bf5282c5bf422f4a16d93ace77b57/Lib/webbrowser.py#L552-L595

**Comment by laurentsimon** [comment]
> Also, in the future: please use the dedicated bug template! That template gives us additional context that makes triaging these kinds of possible bugs much faster.

I used the `Issue: Issue or Enhancement` issue and did not change the template.

Thanks for the info. I think it's a problem with my env. I'll close the issue. That's enough info for me to go and test things out. Thank you!

**Comment by woodruffw** [comment]
> I used the `Issue: Issue or Enhancement` issue and did not change the template.

Gotcha -- that template's title is definitely a little ambiguous, sorry about that! It's intended for feature proposals and discussions, not bug reports. I'll fix that.

The bug report template is right above it, with the title "Bug."

> I think it's a problem with my env. I'll close the issue. That's enough info for me to go and test things out. Thank you!

Let us know if you continue to have issues -- we're happy to reopen and root-cause further. It's possible that `webbrowser`'s defaults are just bad, in which cause we should override them!
