### ISSUE TITLE
Consolidate the sign API

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/sigstore-python#665]
**Description**

The existing `sign()` takes a limited number of inputs, and it may be useful to have an `options` input to add more flexible options. Example:
- `SIGSTORE_OAUTH_FORCE_OOB` is currently an env variable which needs to be set prior to calling the API. Should it not be an input to the signing function instead?
- Signing currently support `hashedrekord`, but this may change in the future to support intoto types

I wonder whether it'd make sense to consolidate the API.

**Comment by laurentsimon** [comment]
> > * `SIGSTORE_OAUTH_FORCE_OOB` is currently an env variable which needs to be set prior to calling the API. Should it not be an input to the signing function instead?
> 
> I might be misunderstanding what you mean, but I don't think this is true -- the current `Signer.sign()` API takes an identity token that's been pre-retrieved, so that environment variable shouldn't affect it. 

The example shows using `Issuer.get_identity_token()` in https://github.com/sigstore/sigstore-python/blob/main/sigstore/sign.py#L26, which uses the env variable https://github.com/sigstore/sigstore-python/blob/main/sigstore/oidc.py#L264. If the token is passed as a string by a user, you're right it works. But if doing the OAuth flow, how should the caller create the token?

**Comment by woodruffw** [comment]
Okay, I understand what you mean now -- you're talking about the `identity_token()` API, not the signing API. I don't think of the former as a part of the signing API, but it's reasonable to consider it part of it.

I agree that should become a parameter on `identity_token()`, rather than an environment variable. I'd be happy to accept a PR for it, otherwise I'll do it when I have a free moment 🙂

**Comment by laurentsimon** [comment]
I sent https://github.com/sigstore/sigstore-python/pull/667

**Comment by woodruffw** [comment]
Done with #667 I believe. Please ping if I got this wrong!
