### ISSUE TITLE
python.org Sigstore documentation doesn't have example for .sigstore bundles

### ISSUE THREAD

**Issue by sethmlarson** [sigstore/sigstore-python#687]
Cross-posting [this issue](https://github.com/python/pythondotorg/issues/2285) due to the note at the bottom of [the page](https://www.python.org/download/sigstore/):

> Any issues with this guide can be reported to https://github.com/sigstore/sigstore-python/issues

If this isn't appropriate for this particular issue feel free to close (and perhaps we need to clarify what types of issues we're expecting from that message?)

**Comment by woodruffw** [comment]
Thanks! I _think_ that message was intended more for errors coming from the `sigstore` CLI and not documentation issues, but it reached the right audience nonetheless 🙂 

I'll follow up on the original issue you opened!
