### ISSUE TITLE
Certificate timestamp issue when checking for validity datetime

### ISSUE THREAD

**Issue by perone** [sigstore/sigstore-python#700]
The field `not_valid_after` in the certificate is not tz-aware, therefore when a check is done using this timestamp it will assume that it is localtime, changing the timestamp and causing the sign operation to always trigger a `ExpiredCertificate`.

Reproduces in version: `main` (2.0.0rc1)

**Comment by woodruffw** [comment]
Thanks for catching this @perone, and for using our release candidate! I'll take a look at #701 now.
