### ISSUE TITLE
Error: "Clone succeeded, but checkout failed"

### ISSUE THREAD

**Issue by lmmx** [sigstore/sigstore-python#734]
**Description**

I tried to clone with

```sh
git clone git@github.com:sigstore/sigstore-python.git
```

and got

```sh
Cloning into 'sigstore-python'...                                                                   
remote: Enumerating objects: 3962, done.                                                            
remote: Counting objects: 100% (1043/1043), done.                                                   
remote: Compressing objects: 100% (283/283), done.                                                  
remote: Total 3962 (delta 893), reused 830 (delta 760), pack-reused 2919                            
Receiving objects: 100% (3962/3962), 1.14 MiB | 3.76 MiB/s, done.                                   
Resolving deltas: 100% (2795/2795), done.                                                           
error: unable to create file test/unit/assets/staging-tuf/targets/3d035f94e1b14ac84627a28afdbed9a34861fb84239f76d73aa1a99f52262bfd95c4fa0ee71f1fd7e3bfb998d89cd5e0f0eafcff9fa7fa87c6e23484fc1e0cec.ctfe_2022_2.pub: File name too long
error: unable to create file test/unit/assets/staging-tuf/targets/90659875a02f73d1026055427c6d857c556e410e23748ff88aeb493227610fd2f5fbdd95ef2a21565f91438dfb3e073f50c4c9dd06f9a601b5d9b064d5cb60b4.fulcio_intermediate.crt.pem: File name too long                                                                                                
error: unable to create file test/unit/assets/staging-tuf/targets/fa2ca05656176f993fd616fa8586f3deeaacfb891dfb6f58e02b26073cb0233a52b7e66338d0053c8549f551485581141094c2de40ca812d8ac47a128bf84963.trusted_root.json: File name too long
fatal: unable to checkout working tree                                                              
warning: Clone succeeded, but checkout failed.   
You can inspect what was checked out with 'git status'                                              
and retry with 'git restore --source=HEAD :/' 
```

Never encountered this before! :sweat_smile: No big deal if it's difficult to fix, I was just hoping to look at the files locally to get a better understanding of this project, and I don't need these files to do so (but it does mean it's not possible for me to get a clean git tree: `git status` reports various directories as "deleted" and `git stash -a` fails for the same reason the checkout does)

```
error: lstat("test/unit/assets/staging-tuf/targets/3d035f94e1b14ac84627a28afdbed9a34861fb84239f76d73aa1a99f52262bfd95c4fa0ee71f1fd7e3bfb998d89cd5e0f0eafcff9fa7fa87c6e23484fc1e0cec.ctfe_2022_2.pub"): File name too long
fatal: Unable to process path test/unit/assets/staging-tuf/targets/3d035f94e1b14ac84627a28afdbed9a34861fb84239f76d73aa1a99f52262bfd95c4fa0ee71f1fd7e3bfb998d89cd5e0f0eafcff9fa7fa87c6e23484fc1e0cec.ctfe_2022_2.pub
Cannot save the current worktree state
```

**Version**

main branch ec5d403

**Comment by woodruffw** [comment]
Thanks for the report!

That's an extremely weird failure mode 🙂 -- it looks like your host OS doesn't like how long those (admittedly very long) unit test asset paths are. 

Could you share some more details about your host? This should be sufficient:

* OS type (e.g. Windows, Mac)
* Filesystem type if you know it
* `git` version

**Comment by woodruffw** [comment]
Context:

```python
>>> len("test/unit/assets/staging-tuf/targets/3d035f94e1b14ac84627a28afdbed9a34861fb84239f76d73aa1a99f52262bfd95c4fa0ee71f1fd7e3bfb998d89cd5e0f0eafcff9fa7fa87c6e23484fc1e0cec.ctfe_2022_2.pub")

181
```

So these are long, but they're not _crazy_ long -- 255-260 is the normal maximum range for filename lengths and this is well below that, although it's possible that it gets pushed just over the limit with whatever directory you're cloning into.

**Comment by woodruffw** [comment]
CC @tnytown as well, since you renamed these to include their hashes -- do you know if we need this?

**Comment by lmmx** [comment]
Hey sorry for delay @woodruffw 

- OS: Linux Mint

```sh
lsb_release -a
```
> Distributor ID:	Linuxmint
> Description:	Linux Mint 20.2
> Release:	20.2
> Codename:	uma

- Filesystem type: ext4 (`df -T | grep "^/dev" | grep " /$" | awk '{print $2}'`)
- git version: git version 2.25.1

I am using an encrypted hard drive `ecryptfs`, the service ships with Linux Mint and I think it's responsible for the limits. I understand it's on Ubuntu (Linux Mint's base) too 

> If filenames are encrypted, things get a little more complicated. eCryptfs prepends a bit of data on the front of the encrypted filename, such that it can identify encrypted filenames definitively. Also, the encryption itself involves "padding" the filename.

-- [via](https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs)

**Comment by woodruffw** [comment]
Thanks for the info, and for the context re: `ecryptfs`.

Unfortunately, I'm, not sure there's a ton we can do here: TUF itself (for better or worse) prepends these hashes for consistent snapshots, so the `git clone` failure here is probably foreshadowing a similar failure that'll happen when you attempt to run `sigstore sign ...`.

We do indeed have users running on Ubuntu, so I think the failure mode here is squarely in `ecryptfs`'s court: a limitation on filenames longer than 143 characters is a pretty substantial one, and I wouldn't be surprised if other software has similar issues with it (including anything that allows non-ASCII UTF-8 in filenames). 

It might be worth raising this upstream with TUF (this hashes look ludicrously long to me, well outside of any reasonable security margin, plus they could probably be more compactly encoded than hex-encoding), but as a downstream dependent on TUF we're somewhat constrained here.

**Comment by lmmx** [comment]
Yeah as I say I am unfamiliar with the codebase (since I can't even download it aha), if you say it's a won't fix fair enough

**Comment by jku** [comment]
I totally agree with William here: the limit set by ecryptfs is surprising and substantial, expecting other projects to comply with that is probably unrealistic...

That said, TUF implementations don't in practice need to store actual files with these filenames: The repository just needs to serve _URLS_ that contain the filename and client needs to download that URL.

So the tests absolutely can be refactored so that the files do not have names like this: I've not looked at how the files are used so I have not idea if that would be worth the effort.
