### ISSUE TITLE
Unclear error message "GCP: OIDC token request failed (code=404)"

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/sigstore-python#738]
I tried signing on a GCE machine. I received error "GCP: OIDC token request failed (code=404)"

Running:
```shell
$curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/service-accounts/default/identity
{"error":"invalid_request","error_description":"Service account not enabled on this instance"}
```

Maybe it would help to relay this error to the user, at least if the tool is run in a debug / verbose mode?

/cc @di

**Comment by woodruffw** [comment]
Thanks for the report @laurentsimon! 

This has been fixed upstream in https://github.com/di/id/pull/93; we'll need to cut a new release there and bump here. I'll reopen this to track that, and close when we do.

**Comment by woodruffw** [comment]
#767 bumps `id`, which will address the ambiguous error message here. Thanks again @laurentsimon!
