### ISSUE TITLE
make SigningResult._to_bundle() public

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#763]
**Description**

`SigningResult._to_bundle()` should be a public method: This would enable signing applications to use the bundle format.
* The bundle is already part of the CLI  interface
* `verify` already contains similar public API (as `VerificationMaterials.from_bundle()` is public)

**Comment by woodruffw** [comment]
I was keeping this private for a reason, but I can no longer remember that reason. So I think this is fine to make public 🙂
