### ISSUE TITLE
Pages deploy fails on main

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#849]
**Description**

Upgrading deploy-pages to v4 broke deployment (because it requires upload-pages-artifact v3).

So I upgraded upload-pages-artifact... but now deploy fails with

`Error: Failed to create deployment (status: 400) with build version 8ef04db1d705a03e46853ab0431fcf376fe87318. Responded with: No artifact_url provided`

https://github.com/sigstore/sigstore-python/actions/runs/7272426379

**Comment by jku** [comment]
This seems to be actions/deploy-pages#286. 

The GH artifact actions upgrade really isn't a great experience so far...

**Comment by woodruffw** [comment]
Yeah, this is now the 4th distinct issue I've seen with the new version rollouts. 

IMHO we can let this fail for a bit -- the current pages are still up and document the currently stable released API, so a fix doesn't become pressing until we do another release. Hopefully they figure this out by then 🙂

**Comment by jku** [comment]
Github has done some internal fixes as the same job now succeeds.

I'll leave this open for now to see a few more successful ones since there's still something I don't understand:
the updated documentation claims that `actions: read` is somehow now required to download the artifact... But we don't have that and everything still seems to work?

**Comment by jku** [comment]
Seems to work just fine 🤷‍♂️
