### ISSUE TITLE
API: Remove `SigningResult`

### ISSUE THREAD

**Issue by woodruffw** [sigstore/sigstore-python#854]
Per discussion in #804: `SigningResult` is now mostly an internal duplication of a `Bundle`, so we should just use `Bundle` directly.

This will be a breaking API change, so slating for 3.0.

**Comment by tetsuo-cpp** [comment]
@woodruffw I can do this just before we cut 3.0. I assume we wouldn't want this in immediately since it would introduce breaking changes to any point releases that we need to make between now and then.

**Comment by woodruffw** [comment]
Makes sense to me!

**Comment by woodruffw** [comment]
#860 is making this a little more pressing, so I'll do this today.
