### ISSUE TITLE
`sigstore.verify` should check signing cert inclusion in the CT log

### ISSUE THREAD

**Issue by tnytown** [sigstore/sigstore-python#886]
`sigstore-python` doesn't currently check the signing cert's presence in the CT log in the `verify` flow, but we are required to per the Sigstore Client specs:

> Verifier MUST extract the `SignedCertificateTimestamp` embedded in the leaf certificate, and verify it as in [RFC 9162 §8.1.3](https://datatracker.ietf.org/doc/html/rfc9162#name-validating-scts), using the verification key from the Certificate Transparency Log.

or:

> [...] Instead, Verifiers MAY perform online verification by fetching and validating inclusion proofs ([RFC 9162 §8.1.4](https://datatracker.ietf.org/doc/html/rfc9162#name-fetching-inclusion-proofs)) against a signed tree head. The Verifier SHOULD fetch the signed tree head in a manner that prevents equivocation by the Certificate Transparency log (e.g., by requiring signatures from independent “witnesses”).

**Comment by haydentherapper** [comment]
Is this referring to online verification? From what I can tell in the code, the SCT is checked, which should be sufficient as an offline "proof". I would not recommend implementing the online verification check, as online verification adds latency to verification and decreases privacy (the log knows when an identity is used). I would add a flag that allows a verifier to opt out of checking the SCT (if that does not yet exist).

**Comment by haydentherapper** [comment]
Oh sorry! You're right, I need to look at file names.

**Comment by javanlacerda** [comment]
I'm working on it :)
