### ISSUE TITLE
Support other signature and hash types

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/sigstore-python#95]
We have some hardcoded assumptions that we're using ECDSA keys with SHA256 hashes to generate signatures. Fulcio supports other signing and hashing algorithms so we should allow them too. For example, the staging instance is currently using an RSA CTFE key for signing.

**Comment by woodruffw** [comment]
> Fulcio supports other signing and hashing algorithms so we should allow them too.

Yep. I'll double-check this, but I think the parameters we specifically need to support are:

* RSA (>= 2048-bit only) + SHA256
* ECDSA + SHA256

It might make sense to support other hash algorithms as well, but I believe Fulcio only uses SHA256 at the moment.

**Comment by woodruffw** [comment]
Let's prioritize this after embedded SCT support (#30); that PR will probably be over-restrictive, which is fine for now.

**Comment by tetsuo-cpp** [comment]
@woodruffw Sorry, I linked this issue to #84. From your comment, sounds like there's still more to do here.

I can take a look at it tomorrow. What did you have in mind?

**Comment by woodruffw** [comment]
No problem. Yeah, I think the only thing left to do here is to relax some of the checks in #84. But they're not currently impacting any active instances (that we know of), so I think we can hold off here until the cryptography release lands.

**Comment by woodruffw** [comment]
I _think_ this is now done, at least for the CTFE keys.
