### ISSUE TITLE
pin securesystemslib in 2.1.x series

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#960]
Since the next release is a pretty big API change, it might be safest if we pin securesystemslib in 2.1.x branch already. This was already fixed in main by constraining python-tuf to 4.x (as python-tuf is now more strict about securesystemslib).

See comment in #958 for more detail.

I'll do a PR, we can still discuss if this is needed or not

**Comment by woodruffw** [comment]
Agreed and merged in #960, so closing.
