### ISSUE TITLE
Wrong identity provider

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/sigstore-python#970]
**Description**

I signed (using the API) with a Google account, and the OIDC token issuer shows `https://oauth2.sigstore.dev/auth`. I expected the value to be `https://accounts.google.com`.

Verification works when passing my email as identity and `https://accounts.google.com` as the identity provider.

**Version**

At main

**Comment by woodruffw** [comment]
> I signed (using the API) with a Google account, and the OIDC token issuer shows `https://oauth2.sigstore.dev/auth`. I expected the value to be `https://accounts.google.com`.

Could you share the API calls you made? If you used `Issuer.identity_token()` and went through the interactive flow, that took you through Sigstore's Dex instance rather than directly through the Google OIDC IdP.

**Comment by laurentsimon** [comment]
Gotcha. The main problem is that the CLI / API (for model signing) is generic and I don't know ahead of time which IdP users will be using. I think what I'm after is some UX improvement. Thinking more about that, I should be able to extract the IdP from the cert after signing occurred. That would resolve the problem. Feel free to close this issue and I'll fix it in our codebase. Thanks

**Comment by woodruffw** [comment]
Ah yeah, I think a variant of this has cropped up before (#567?) -- if you need to stop the user from signing using an OIDC issuer other than the one you expect but you can't stop them from performing the OIDC flow itself, you _should_ be able to introspect on `IdentityToken.expected_certificate_subject`. Does that help address the case?

(cc @jku since he also hit this, IIRC)

**Comment by susperius** [comment]
I ran into the same issue. Is there something that contains the real issuer? (i.e. Google) 

I'm using the `issuer.identity_token` call to retrieve the token with the issuer being the production instance.

**Comment by woodruffw** [comment]
> I ran into the same issue. Is there something that contains the real issuer? (i.e. Google)

It's mentioned directly above: `IdentityToken.expected_certificate_subject`.

For example:

```python
>>> from sigstore import oidc
>>> issuer = oidc.Issuer.production()
>>> token = issuer.identity_token()
Waiting for browser interaction...
>>> token
<sigstore.oidc.IdentityToken object at 0x102673230>
>>> token.expected_certificate_subject
'https://accounts.google.com'
```

**Comment by woodruffw** [comment]
(I don't remember why it's called the "expected certificate subject" rather than "federated issuer" or similar. It might make sense to rename it.)

**Comment by woodruffw** [comment]
I believe this is fully addressed by pre-existing APIs on `IdentityToken`, so closing 🙂
