### ISSUE TITLE
Set user-agent in all HTTP requests

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#985]
**Description**

It would be useful if sigstore-python had a user-agent  in all requests:

- [x] fulcio client (#1008)
- [x] rekor client (#1008)
- [ ] tuf client (I've just added this into python-tuf so we can use it when next release comes)
- [x] oidc (#1008)

Current user-agent is `python-requests/2.31.0`. I think `sigstore-python/X.Y.Z python-requests/2.31.0` (or just `sigstore-python/X.Y.Z`) would make sense.

This can be implemented one client at a time.

**Comment by woodruffw** [comment]
Great idea!

**Comment by woodruffw** [comment]
Completed as of https://github.com/sigstore/sigstore-python/pull/1017, I believe 🙂
